const fs = require("fs");
const path = require("path");
const vm = require("vm");

const sourceFile = path.join(__dirname, "talent_data_official_full.js");
const outDir = path.join(__dirname, "wxapp", "data");
const outFile = path.join(outDir, "talent-data.js");

if (!fs.existsSync(sourceFile)) {
  throw new Error(`Source file not found: ${sourceFile}`);
}

const code = fs.readFileSync(sourceFile, "utf8");
const context = { window: {} };
vm.createContext(context);
vm.runInContext(code, context, { filename: sourceFile });

const talentData = context.window.TALENT_DATA || {};
const classList = context.window.TALENT_CLASS_LIST || Object.keys(talentData).map((id) => ({ id }));

fs.mkdirSync(outDir, { recursive: true });

const payload = {
  TALENT_DATA: talentData,
  TALENT_CLASS_LIST: classList
};

const output = [
  "// Auto-generated by build_wx_talent_data.js",
  "module.exports = " + JSON.stringify(payload, null, 2) + ";",
  ""
].join("\n");

fs.writeFileSync(outFile, output, "utf8");
console.log(`Generated: ${outFile}`);
