// Complete talent data extracted from official talents.turtlecraft.gg
// This data includes: icon names, ranks, descriptions, and tree positions

const talentData = {
    warrior: {
        name: "战士",
        color: "#C79C6E",
        icon: "class_warrior.png",
        trees: [
            {
                name: "Arms",
                nameCn: "武器",
                maxPoints: 49,
                talents: [
                    { name: "Improved Heroic Strike", icon: "ability_rogue_ambush", maxRanks: 3, row: 0, col: 0, requires: null, desc: "Reduces the cost of your Heroic Strike ability by [1/2/3] rage points." },
                    { name: "Tactical Mastery", icon: "spell_nature_enchantarmor", maxRanks: 5, row: 0, col: 1, requires: null, desc: "You retain up to [5/10/15/20/25] of your rage points when you change stances." },
                    { name: "Improved Rend", icon: "ability_gouge", maxRanks: 2, row: 0, col: 2, requires: null, desc: "Increases the bleed damage done by your Rend ability by [10/20]%." },
                    { name: "Improved Charge", icon: "ability_warrior_charge", maxRanks: 2, row: 1, col: 0, requires: null, desc: "Increases the amount of rage generated by your Charge ability by [5/10]." },
                    { name: "Deflection", icon: "ability_parry", maxRanks: 5, row: 1, col: 1, requires: null, desc: "Increases your Parry chance by [1/2/3/4/5]%." },
                    { name: "Improved Thunder Clap", icon: "ability_thunderclap", maxRanks: 3, row: 2, col: 0, requires: null, desc: "Reduces the cost of your Thunder Clap ability by [1/2/4] rage point and increases the damage by [20/40/60]%." },
                    { name: "Master Strike", icon: "master_strike_1", maxRanks: 1, row: 2, col: 1, requires: null, desc: "Performs a skillful attack, dealing 35% weapon damage." },
                    { name: "Improved Overpower", icon: "inv_sword_05", maxRanks: 2, row: 2, col: 2, requires: null, desc: "Increases the critical strike chance of your Overpower ability by [25/50]%." },
                    { name: "Deep Wounds", icon: "ability_backstab", maxRanks: 3, row: 3, col: 0, requires: {talent: 2, ranks: 2}, desc: "Your critical strikes cause the opponent to bleed, dealing [20/40/60]% of your melee weapon's average damage over 6 sec." },
                    { name: "Two-Handed Weapon Specialization", icon: "inv_axe_09", maxRanks: 3, row: 4, col: 0, requires: {talent: 9, ranks: 1}, desc: "Increases the damage you deal with two-handed melee weapons by [2/4/6]%." },
                    { name: "Impale", icon: "ability_searingarrow", maxRanks: 2, row: 4, col: 1, requires: {talent: 9, ranks: 1}, desc: "Increases the critical strike damage bonus of your abilities by [10/20]%." },
                    { name: "Sweeping Strikes", icon: "ability_rogue_slicedice", maxRanks: 1, row: 5, col: 0, requires: {talent: 13, ranks: 3}, desc: "Your attacks strike both your target and a nearby enemy." },
                    { name: "Master of Arms", icon: "garrison_weaponupgrade", maxRanks: 5, row: 5, col: 1, requires: {talent: 8, ranks: 1}, desc: "Adds effects based on weapon type." },
                    { name: "Mortal Strike", icon: "ability_warrior_savageblow", maxRanks: 1, row: 7, col: 0, requires: {talent: 17, ranks: 1}, desc: "A vicious strike that deals 115% weapon damage and wounds the target." }
                ]
            },
            {
                name: "Fury",
                nameCn: "狂暴",
                maxPoints: 55,
                talents: [
                    { name: "Booming Voice", icon: "spell_nature_purge", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases the area of effect of all shouts by [12/24/36/48/60]%." },
                    { name: "Cruelty", icon: "ability_rogue_eviscerate", maxRanks: 5, row: 0, col: 2, requires: null, desc: "Increases your chance to get a critical strike with melee weapons by [1/2/3/4/5]%." },
                    { name: "Dual Wield Specialization", icon: "ability_dualwield", maxRanks: 5, row: 1, col: 1, requires: null, desc: "Increases the damage done by your off-hand weapon by [5/10/15/20/25]%." },
                    { name: "Unbridled Wrath", icon: "spell_nature_stoneclawtotem", maxRanks: 5, row: 1, col: 2, requires: null, desc: "Increases the rage generated by your Enrage ability." },
                    { name: "Improved Whirlwind", icon: "ability_whirlwind", maxRanks: 3, row: 3, col: 1, requires: null, desc: "Reduces the cooldown of your Whirlwind ability by [1/1/2] sec." },
                    { name: "Bloodthirst", icon: "spell_nature_bloodlust", maxRanks: 1, row: 7, col: 1, requires: null, desc: "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power." }
                ]
            },
            {
                name: "Protection",
                nameCn: "防护",
                maxPoints: 53,
                talents: [
                    { name: "Improved Bloodrage", icon: "ability_racial_bloodrage", maxRanks: 2, row: 0, col: 0, requires: null, desc: "Increases the instant Rage generated by your Bloodrage ability by [5/10]." },
                    { name: "Shield Specialization", icon: "inv_shield_06", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases your chance to block attacks with a shield by [1/2/3/4/5]%." },
                    { name: "Anticipation", icon: "spell_nature_mirrorimage", maxRanks: 3, row: 0, col: 2, requires: null, desc: "Increases your Dodge chance by [2/4/6]%." },
                    { name: "Iron Will", icon: "spell_magic_magearmor", maxRanks: 5, row: 1, col: 0, requires: null, desc: "Increases your resistance to Stun and Fear effects by [5/10/15/20/25]%." },
                    { name: "Toughness", icon: "spell_holy_devotion", maxRanks: 5, row: 1, col: 1, requires: null, desc: "Increases your Armor value from items by [2/4/6/8/10]%." },
                    { name: "Last Stand", icon: "spell_holy_ashestoashes", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 2}, desc: "When activated, this ability temporarily grants you 30% of your maximum hit points." },
                    { name: "Improved Intervene", icon: "ability_warrior_intervene", maxRanks: 2, row: 2, col: 1, requires: null, desc: "Increases the range of your Intervene by [5/10] yards." },
                    { name: "Improved Taunt", icon: "spell_nature_reincarnation", maxRanks: 2, row: 2, col: 2, requires: null, desc: "Reduces the cooldown of your Taunt ability by [2/4] sec." },
                    { name: "Improved Revenge", icon: "ability_warrior_revenge", maxRanks: 3, row: 3, col: 0, requires: null, desc: "Increases the damage dealt by your Revenge ability by [25/50]%." },
                    { name: "Shield Slam", icon: "inv_shield_05", maxRanks: 1, row: 6, col: 0, requires: {talent: 14, ranks: 5}, desc: "Slam the target with your shield, causing damage based on your block value." },
                    { name: "One-Handed Weapon Specialization", icon: "inv_sword_20", maxRanks: 5, row: 6, col: 1, requires: null, desc: "Increases the damage you deal with one-handed melee weapons by [2/4/6/8/10]%." },
                    { name: "Defensive Tactics", icon: "ability_warrior_stalwartprotector", maxRanks: 3, row: 7, col: 1, requires: null, desc: "While in Defensive Stance, you deal [5/10/15]% more damage." }
                ]
            }
        ]
    },
    // Other classes would follow the same pattern...
    paladin: {
        name: "圣骑士",
        color: "#F58CBA",
        icon: "class_paladin.png",
        trees: [
            { name: "Holy", nameCn: "神圣", maxPoints: 45, talents: [
                { name: "Divine Strength", icon: "spell_holy_holybolt", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases your Strength by [2/4/6/8/10]%." },
                { name: "Spiritual Focus", icon: "spell_holy_searinglight", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Gives your Holy spells a [14/28/42/56/70]% chance to not get interrupted." },
                { name: "Healing Light", icon: "spell_holy_layonhands", maxRanks: 3, row: 0, col: 2, requires: null, desc: "Increases the healing done by your Holy spells by [4/7/10]%." },
                { name: "Consecration", icon: "spell_holy_prayerofhealing", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 5}, desc: "Consecrates the land beneath you, causing Holy damage to enemies." },
                { name: "Illumination", icon: "spell_holy_flashheal", maxRanks: 5, row: 3, col: 0, requires: null, desc: "After casting a Holy spell, you have a [10/20/30/40/50]% chance to gain Mana." }
            ]},
            { name: "Protection", nameCn: "防护", maxPoints: 50, talents: [
                { name: "Holy Shield", icon: "spell_holy_blessedresilience", maxRanks: 4, row: 0, col: 0, requires: null, desc: "When you block, you have a chance to heal for [40/80/120/160]." },
                { name: "Redoubt", icon: "spell_holy_eyeforaneye", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases your chance to block by [10/20/30/40/50]% and your Defense skill by [2/4/6/8/10]." },
                { name: "Blessing of Sanctuary", icon: "spell_holy_greaterblessingofsanctuary", maxRanks: 1, row: 1, col: 0, requires: {talent: 0, ranks: 4}, desc: "Blessing that adds damage to melee attacks." }
            ]},
            { name: "Retribution", nameCn: "惩戒", maxPoints: 45, talents: [
                { name: "Improved Judgment", icon: "spell_holy_righteousjudgment", maxRanks: 2, row: 0, col: 0, requires: null, desc: "Decreases the cooldown of your Judgment ability by [1/2] sec." },
                { name: "Conviction", icon: "spell_holy_retribution", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases your chance to get a critical strike by [1/2/3/4/5]%." },
                { name: "Crusader Strike", icon: "spell_holy_crusaderstrike", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 5}, desc: "A strike that deals melee damage." }
            ]}
        ]
    },
    hunter: {
        name: "猎人",
        color: "#ABD473",
        icon: "class_hunter.png",
        trees: [
            { name: "Beast Mastery", nameCn: "野兽控制", maxPoints: 51, talents: [
                { name: "Improved Aspect of the Hawk", icon: "spell_nature_ravenform", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases ranged attack power by [10/20/30/40/50]% while Aspect of the Hawk is active." },
                { name: "Fervor", icon: "ability_hunter_beastcall", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 5}, desc: "Send your pet to attack." },
                { name: "Bestial Wrath", icon: "ability_druid_feralcharge", maxRanks: 1, row: 3, col: 0, requires: {talent: 4, ranks: 1}, desc: "Send your pet into a rage." }
            ]},
            { name: "Marksmanship", nameCn: "射击", maxPoints: 51, talents: [
                { name: "Improved Serpent Sting", icon: "ability_hunter_aimedshot", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases the damage of your Serpent Sting by [4/8/12/16/20]%." },
                { name: "Aimed Shot", icon: "inv_spear_07", maxRanks: 1, row: 1, col: 0, requires: {talent: 0, ranks: 5}, desc: "An aimed shot that increases damage." },
                { name: "Rapid Fire", icon: "ability_hunter_runningshot", maxRanks: 1, row: 2, col: 0, requires: null, desc: "Increases ranged attack speed by [40/40]% for 15 sec." },
                { name: "Trueshot Aura", icon: "ability_trueshot", maxRanks: 1, row: 3, col: 0, requires: {talent: 9, ranks: 3}, desc: "Increases the attack power of party members." }
            ]},
            { name: "Survival", nameCn: "生存", maxPoints: 45, talents: [
                { name: "Monster Slaying", icon: "inv_misc_head_dragon_01", maxRanks: 3, row: 0, col: 0, requires: null, desc: "Increases damage against Beasts and Humanoids by [3/6/10]%." },
                { name: "Scatter Shot", icon: "ability_hunter_scattershot", maxRanks: 1, row: 1, col: 0, requires: null, desc: "A shot that causes the target to wander in confusion." }
            ]}
        ]
    },
    rogue: {
        name: "盗贼",
        color: "#FFF569",
        icon: "class_rogue.png",
        trees: [
            { name: "Assassination", nameCn: "刺杀", maxPoints: 50, talents: [
                { name: "Improved Eviscerate", icon: "ability_rogue_eviscerate", maxRanks: 3, row: 0, col: 0, requires: null, desc: "Increases the damage of your Eviscerate by [15/30/45]%." },
                { name: "Malice", icon: "ability_racial_avatar", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases your chance to get a critical strike by [1/2/3/4/5]%." },
                { name: "Ruthlessness", icon: "ability_rogue_ruthlessness", maxRanks: 3, row: 1, col: 0, requires: null, desc: "Your finishing moves have a chance to not consume combo points." }
            ]},
            { name: "Combat", nameCn: "战斗", maxPoints: 50, talents: [
                { name: "Improved Sinister Strike", icon: "ability_rogue_sinisterstrike", maxRanks: 2, row: 0, col: 0, requires: null, desc: "Reduces the Energy cost of your Sinister Strike by [3/5]." },
                { name: "Dual Wield Specialization", icon: "ability_dualwield", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases the damage done by your off-hand weapon by [5/10/15/20/25]%." },
                { name: "Blade Flurry", icon: "ability_warrior_punishingblow", maxRanks: 1, row: 2, col: 0, requires: {talent: 1, ranks: 5}, desc: "Your off-hand weapon strikes also strike the target." }
            ]},
            { name: "Subtlety", nameCn: "敏锐", maxPoints: 50, talents: [
                { name: "Elusiveness", icon: "spell_magic_lesserinvisibilty", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases your Dodge chance by [2/4/6/8/10]%." },
                { name: "Ghostly Strike", icon: "ability_rogue_ghostlystrike", maxRanks: 1, row: 1, col: 0, requires: null, desc: "A strike that has a chance to render the target unable to attack." }
            ]}
        ]
    },
    priest: {
        name: "牧师",
        color: "#FFFFFF",
        icon: "class_priest.png",
        trees: [
            { name: "Discipline", nameCn: "戒律", maxPoints: 50, talents: [
                { name: "Unbreakable Will", icon: "spell_magic_manareduction", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases your resistance to Stun and Fear effects by [5/10/15/20/25]%." },
                { name: "Twin Disciplines", icon: "spell_holy_twindisciplines", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases your spell damage and healing by [2/4/6/8/10]%." }
            ]},
            { name: "Holy", nameCn: "神圣", maxPoints: 50, talents: [
                { name: "Healing Focus", icon: "spell_holy_healingfocus", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Gives your healing spells a [14/28/42/56/70]% chance to not get interrupted." },
                { name: "Divine Grace", icon: "spell_holy_layonhands", maxRanks: 3, row: 1, col: 0, requires: null, desc: "After casting a healing spell, gives the target [5/10/15]% increased healing." }
            ]},
            { name: "Shadow", nameCn: "暗影", maxPoints: 50, talents: [
                { name: "Spirit Tap", icon: "spell_holy_spirittap", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Killing blows give you [5/10/15/20/25]% of your mana back." },
                { name: "Mind Flay", icon: "spell_shadow_siphonmind", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 5}, desc: "Assault the target's mind." }
            ]}
        ]
    },
    shaman: {
        name: "萨满",
        color: "#0070DE",
        icon: "class_shaman.png",
        trees: [
            { name: "Elemental", nameCn: "元素", maxPoints: 50, talents: [
                { name: "Convection", icon: "spell_nature_wispsplode", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the mana cost of your Shock and Stormreach spells by [5/10/15/20/25]%." },
                { name: "Elemental Focus", icon: "spell_holy_mindsooth", maxRanks: 1, row: 1, col: 0, requires: {talent: 0, ranks: 5}, desc: "After landing a critical hit, your next spell has [10/10/10]% reduced mana cost." }
            ]},
            { name: "Enhancement", nameCn: "增强", maxPoints: 50, talents: [
                { name: "Ancestral Knowledge", icon: "spell_shadow_grimward", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases your maximum Mana by [2/4/6/8/10]%." },
                { name: "Feral Spirit", icon: "spell_shadow_summonferalspirit", maxRanks: 1, row: 3, col: 0, requires: {talent: 14, ranks: 3}, desc: "Summon two wolves to fight for you." }
            ]},
            { name: "Restoration", nameCn: "恢复", maxPoints: 50, talents: [
                { name: "Healing Way", icon: "spell_nature_healingway", maxRanks: 3, row: 0, col: 0, requires: null, desc: "Your Healing Wave spells have a [33/66/100]% chance to increase healing." },
                { name: "Mana Tide Totem", icon: "spell_frost_manatide", maxRanks: 1, row: 3, col: 0, requires: {talent: 11, ranks: 3}, desc: "Summon a totem that restores mana." }
            ]}
        ]
    },
    mage: {
        name: "法师",
        color: "#40C7EB",
        icon: "class_mage.png",
        trees: [
            { name: "Arcane", nameCn: "奥术", maxPoints: 51, talents: [
                { name: "Arcane Focus", icon: "spell_holy_devotion", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the chance that enemies can resist your Arcane spells by [2/4/6/8/10]%." },
                { name: "Arcane Impact", icon: "spell_arcane_starfire", maxRanks: 3, row: 1, col: 0, requires: null, desc: "Increases the effect of your Arcane Blast, Arcane Missiles and Arcane Explosion by [10/20/30]%." },
                { name: "Presence of Mind", icon: "spell_holy_holybolt", maxRanks: 1, row: 2, col: 0, requires: {talent: 4, ranks: 3}, desc: "Your next spell is instant." }
            ]},
            { name: "Fire", nameCn: "火焰", maxPoints: 51, talents: [
                { name: "Improved Fireball", icon: "spell_fire_flamebolt", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the casting time of your Fireball by [0.1/0.2/0.3/0.4/0.5] sec." },
                { name: "Ignite", icon: "spell_fire_incinerate", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Your critical hits from Fire spells cause the target to burn." },
                { name: "Combustion", icon: "spell_fire_sealoffire", maxRanks: 1, row: 3, col: 0, requires: {talent: 6, ranks: 3}, desc: "Increases your critical hit chance with Fire spells." }
            ]},
            { name: "Frost", nameCn: "冰霜", maxPoints: 51, talents: [
                { name: "Improved Frostbolt", icon: "spell_frost_frostbolt02", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the casting time of your Frostbolt by [0.1/0.2/0.3/0.4/0.5] sec." },
                { name: "Ice Shards", icon: "spell_frost_iceshard", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases the damage of your Ice Shards by [5/10/15/20/25]%." },
                { name: "Ice Block", icon: "spell_frost_frozenice", maxRanks: 1, row: 4, col: 0, requires: {talent: 8, ranks: 3}, desc: "You become immune to all harmful spells." }
            ]}
        ]
    },
    warlock: {
        name: "术士",
        color: "#8787ED",
        icon: "class_warlock.png",
        trees: [
            { name: "Affliction", nameCn: "痛苦", maxPoints: 51, talents: [
                { name: "Suppression", icon: "spell_holy_restoration", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases the damage of your Affliction spells by [1/2/3/4/5]%." },
                { name: "Improved Corruption", icon: "spell_shadow_abominationexplosion", maxRanks: 5, row: 0, col: 1, requires: null, desc: "Increases the damage of your Corruption spell by [2/4/6/8/10]%." },
                { name: "Dark Pact", icon: "spell_shadow_darkritual", maxRanks: 1, row: 2, col: 0, requires: {talent: 1, ranks: 5}, desc: "Drains mana from your pet." }
            ]},
            { name: "Demonology", nameCn: "恶魔", maxPoints: 51, talents: [
                { name: "Demonic Embrace", icon: "spell_shadow_twilight", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Increases your Stamina by [3/6/9/12/15]%." },
                { name: "Soul Link", icon: "spell_shadow_soulleech", maxRanks: 1, row: 2, col: 0, requires: {talent: 2, ranks: 5}, desc: "Your pet's damage also deals damage to you." }
            ]},
            { name: "Destruction", nameCn: "毁灭", maxPoints: 51, talents: [
                { name: "Improved Shadow Bolt", icon: "spell_shadow_shadowbolt", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Your Shadow Bolt critical hits have a [4/8/12/16/20]% chance to increase damage." },
                { name: "Ruin", icon: "spell_shadow_spirittap", maxRanks: 1, row: 2, col: 0, requires: {talent: 1, ranks: 5}, desc: "Increases the critical strike damage bonus of your Destruction spells by [100/100/100]%." },
                { name: "Chaos Bolt", icon: "spell_shadow_shadowfury", maxRanks: 1, row: 4, col: 0, requires: {talent: 9, ranks: 3}, desc: "Hurls a bolt of chaotic fire." }
            ]}
        ]
    },
    druid: {
        name: "德鲁伊",
        color: "#FF7D0A",
        icon: "class_druid.png",
        trees: [
            { name: "Balance", nameCn: "平衡", maxPoints: 50, talents: [
                { name: "Starlight Wrath", icon: "spell_nature_starfall", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the casting time of your Wrath by [0.1/0.2/0.3/0.4/0.5] sec." },
                { name: "Moonkin Form", icon: "spell_nature_forceofnature", maxRanks: 1, row: 3, col: 0, requires: {talent: 6, ranks: 3}, desc: "Transforms you into Moonkin Form." }
            ]},
            { name: "Feral Combat", nameCn: "野性战斗", maxPoints: 50, talents: [
                { name: "Ferocity", icon: "ability_druid_ferociousbite", maxRanks: 5, row: 0, col: 0, requires: null, desc: "Reduces the Energy cost of your finished moves by [2/4/6/8/10]." },
                { name: "Faerie Fire", icon: "spell_nature_faeriefire", maxRanks: 1, row: 2, col: 0, requires: {talent: 0, ranks: 5}, desc: "Shapeshift into Bear Form." },
                { name: "Berserk", icon: "ability_druid_berserk", maxRanks: 1, row: 4, col: 0, requires: {talent: 10, ranks: 5}, desc: "Go into a berserker rage." }
            ]},
            { name: "Restoration", nameCn: "恢复", maxPoints: 50, talents: [
                { name: "Healing Touch", icon: "spell_nature_healingtouch", maxRanks: 3, row: 0, col: 0, requires: null, desc: "Reduces the casting time of your Healing Touch by [0.1/0.2/0.3] sec." },
                { name: "Tree of Life", icon: "spell_nature_treeoflife", maxRanks: 1, row: 3, col: 0, requires: {talent: 11, ranks: 3}, desc: "Transforms you into the Tree of Life." }
            ]}
        ]
    }
};

// Export for use in HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = talentData;
}
